:doctype: article
:icons: font
:source-highlighter: highlightjs
:docname: Javascript SDK





++++

<div align="center">

<h1>Contributing to Modzy's Javascript SDK</h1>

<br>
<br>
<br>
<br>



<img alt="GitHub contributors" src="https://img.shields.io/github/contributors/modzy/sdk-javascript">

<img alt="GitHub last commit" src="https://img.shields.io/github/last-commit/modzy/sdk-javascript">

<img alt="GitHub Release Date" src="https://img.shields.io/github/release-date/modzy/sdk-javascript">

<br>
<br>

<img src="https://img.shields.io/badge/Contributor%20Covenant-v2.0%20adopted-ff69b4.svg" alt="Contributor Covenant" style="max-width:100%;">

</div>

<br>
<br>

<div align="center">
<a href="/README.md" style="text-decoration:none">Readme</a> |
<a href=https://docs.modzy.com/docs style="text-decoration:none">Documentation</a>

</div>

<br>
<br>
<br>
<br>

++++

Contributions are welcome and they are greatly appreciated! Every little bit helps, and credit will always be given.

Below you'll find our contributing requirements, a step-by-step guideline, and our features roadmap.


== Requirements

- Search previous link:https://github.com/modzy/sdk-javascript/issues[issues] before making new ones to avoid duplicates.
- If you are reporting a bug, please include:
  . Your operating system name and version.
  . Any details about your local setup that might be helpful in troubleshooting.
  . Detailed steps to reproduce the bug.
- If you are proposing a feature:
  . Explain in detail how it would work.
  . Keep the scope as narrow as possible, to make it easier to implement.
  . Remember that this is a volunteer-driven project, and that contributions are welcome.
- File an issue to let us know what you're working on.
- Fork the repo, develop and test your code changes, and add supporting documentation.
- Use descriptive comments throughout your code.
- Add test cases and comment them.
//- Check your spelling and grammar.
- Use descriptive commit messages that clearly explain the changes. Reference the original issue in the pull request.
- Make an individual pull r